# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official
android.nonTransitiveRClass=true
android.useAndroidX=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
