#!/bin/sh
# Gradle start-up script for UN*X. Generated by `gradle wrapper`.
# NOTE: the wrapper jar must exist at gradle/wrapper/gradle-wrapper.jar.
# If it is missing, run `gradle wrapper` once from an installed Gradle.
